driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
    run_list: selinux::disabled
  - name: centos-6.7
    run_list: selinux::disabled
  - name: centos-7.2
    run_list: selinux::disabled
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: fedora-22
    run_list: yum::dnf_yum_compat
  - name: fedora-23
    run_list: yum::dnf_yum_compat
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  - name: ubuntu-16.04
    run_list: apt::default
  - name: opensuse-13.2
  - name: omnios-r151014
    driver:
      box: omnios/r151014

suites:
  #
  # service
  #
  - name: service50-single
    run_list:
    - recipe[mysql_service_test::single]
    includes: [
      'centos-5.11'
    ]
    attributes:
      mysql:
       version: '5.0'

  - name: service51-single
    run_list:
    - recipe[mysql_service_test::single]
    includes: [
      'centos-5.11',
      'centos-6.7'
    ]
    attributes:
      mysql:
       version: '5.1'

  - name: service55-single
    run_list:
    - recipe[mysql_service_test::single]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'debian-7.9',
      'debian-8.2',
      'ubuntu-12.04',
      'ubuntu-14.04',
      'omnios-r151014'
    ]
    attributes:
      mysql:
       version: '5.5'

  - name: service56-single
    run_list:
    - recipe[mysql_service_test::single]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'ubuntu-14.04',
      'opensuse-13.2',
      'omnios-r151014'
    ]
    attributes:
      mysql:
       version: '5.6'

  - name: service57-single
    run_list:
    - recipe[mysql_service_test::single]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'ubuntu-16.04'
    ]
    attributes:
      mysql:
       version: '5.7'

  - name: service50-multi
    run_list:
    - recipe[mysql_service_test::multi]
    includes: [
      'centos-5.11'
    ]
    attributes:
      mysql:
       version: '5.0'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       initial_root_password: 'string with spaces'

  - name: service51-multi
    run_list:
    - recipe[mysql_service_test::multi]
    includes: [
      'centos-5.11'
    ]
    attributes:
      mysql:
       version: '5.1'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       initial_root_password: 'string with spaces'

  - name: service55-multi
    run_list:
    - recipe[mysql_service_test::multi]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'debian-7.9',
      'debian-8.2',
      'ubuntu-12.04',
      'ubuntu-14.04',
      'omnios-r151014'
    ]
    attributes:
      mysql:
       version: '5.5'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       initial_root_password: 'string with spaces'

  - name: service56-multi
    run_list:
    - recipe[mysql_service_test::multi]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'ubuntu-14.04',
      'opensuse-13.2',
      'omnios-r151014'
    ]
    attributes:
      mysql:
       version: '5.6'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       initial_root_password: 'string with spaces'

  - name: service57-multi
    run_list:
    - recipe[mysql_service_test::multi]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'ubuntu-16.04'
    ]
    attributes:
      mysql:
       version: '5.7'
       port: '3308'
       data_dir: '/data/instance-2'
       run_user: 'bob'
       run_group: 'bob'
       initial_root_password: 'string with spaces'

  #
  # client
  #
  - name: client50
    run_list:
    - recipe[mysql_client_test]
    attributes:
      mysql:
       version: '5.0'
    includes: [
      'centos-5.11'
    ]

  - name: client51
    run_list:
    - recipe[mysql_client_test]
    attributes:
      mysql:
       version: '5.1'
    includes: [
      'centos-5.11',
      'centos-6.7'
    ]

  - name: client55
    run_list:
    - recipe[mysql_client_test]
    attributes:
      mysql:
       version: '5.5'
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'debian-7.9',
      'debian-8.2',
      'ubuntu-12.04',
      'ubuntu-14.04',
      'omnios-r151014'
    ]

  - name: client56
    run_list:
    - recipe[mysql_client_test]
    attributes:
      mysql:
       version: '5.6'
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'omnios-r151014'
    ]

  - name: client57
    run_list:
    - recipe[mysql_client_test]
    attributes:
      mysql:
       version: '5.7'
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'ubuntu-16.04'
    ]

  #
  # config
  #
  - name: config50
    run_list:
    - recipe[mysql_config_test]
    includes: [
      'centos-5.11'
    ]
    attributes:
      mysql:
       version: '5.0'

  - name: config51
    run_list:
    - recipe[mysql_config_test]
    includes: [
      'centos-5.11'
    ]
    attributes:
      mysql:
       version: '5.1'

  - name: config55
    run_list:
    - recipe[mysql_config_test]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'debian-7.9',
      'debian-8.2',
      'ubuntu-12.04',
      'ubuntu-14.04',
      'omnios-r151014'
    ]
    attributes:
      mysql:
       version: '5.5'

  - name: config56
    run_list:
    - recipe[mysql_config_test]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'ubuntu-14.04',
      'opensuse-13.2',
      'omnios-r151014'
    ]
    attributes:
      mysql:
       version: '5.6'

  - name: config57
    run_list:
    - recipe[mysql_config_test]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'ubuntu-16.04'
    ]
    attributes:
      mysql:
       version: '5.7'

  #
  # replication-test
  #
  - name: replication-test
    run_list:
    - recipe[mysql_replication_test]
    includes: [
      'centos-5.11',
      'centos-6.7',
      'centos-7.2',
      'fedora-22',
      'fedora-23',
      'debian-7.9',
      'debian-8.2',
      'ubuntu-12.04',
      'ubuntu-14.04',
      'ubuntu-16.04',
      'opensuse-13.2',
      'omnios-r151014'
    ]
